version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  chromatic-deployment:
    docker:
      - image: circleci/node:18.15.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed) e.g. yarn, npm, pnpm
      - run: npm install
        # 👇 Runs the Chromatic CLI
      - run: npm chromatic

workflows:
  # 👇 Adds Chromatic to the workflow
  chromatic-deploy:
    jobs:
      - chromatic-deployment
